// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_ui_Navgation_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Navgation;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Slider1;
lv_obj_t *ui_Label5;
lv_obj_t *ui_SpeechBubble;
lv_obj_t *ui_SpeechTail1;
lv_obj_t *ui_SpeechTail2;
lv_obj_t *ui_Circle;
lv_obj_t *ui_UpperLine;
lv_obj_t *ui_LowerLine;
lv_obj_t *ui_LeftLine;
lv_obj_t *ui_RightLine;
lv_obj_t *ui_VideoRecorderRect;
lv_obj_t *ui_VideoLine1;
lv_obj_t *ui_VideoLine2;
lv_obj_t *ui_VideoLine3;
lv_obj_t *ui_RoundedRect;//电池外框
lv_obj_t *ui_Line;
lv_obj_t *ui_RoundedRect2;
lv_obj_t *ui_SlantedLine;
lv_obj_t *ui_Chinese_status;
lv_obj_t *ui_Chinese_Aitalk;
lv_obj_t *ui_Chinese_Bright;
lv_obj_t *ui_NavTopLeftLabel;
lv_obj_t *ui_StatusLabel;
lv_obj_t *ui_LineA;//电池格数
lv_obj_t *ui_LineB;
lv_obj_t *ui_LineC;
lv_obj_t *ui_LineD;
lv_obj_t *ui_BrightnessLine;
lv_obj_t *ui_AiTalkLine;
lv_obj_t *ui_VideoContainer;
lv_obj_t *ui_Menu3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

// 在ui.c中添加，让main.c能够访问到ui_Label2
//lv_obj_t *ui_Label2;        // 第20行：SquareLine Studio生成的声明
//extern lv_obj_t *ui_Label2; // 第35行：你添加的extern声明

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 8
    #error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
