// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
// 在main.c的全局变量区域添加

void ui_ui_Navgation_screen_init(void)
{
    ui_Navgation = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_Navgation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    
    // 设置屏幕背景为黑色
    lv_obj_set_style_bg_color(ui_Navgation, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Navgation, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    //yf
    lv_obj_set_width(ui_Navgation, 0);
    //yf

    // 顶左角空文字标签，默认无内容，位置(0,0)
    ui_NavTopLeftLabel = lv_label_create(ui_Navgation);
    lv_obj_set_align(ui_NavTopLeftLabel, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(ui_NavTopLeftLabel, 0, 0);
    lv_label_set_text(ui_NavTopLeftLabel, "");
    // 指定字体与颜色
    lv_obj_set_style_text_font(ui_NavTopLeftLabel, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_NavTopLeftLabel, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);



}
