// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
// 在main.c的全局变量区域添加
extern lv_obj_t *ui_Label2;  // 声明外部变量，指向"微笑"标签

// 声明全局变量，供 main.c 使用
lv_obj_t *ui_StatusLabel = NULL;

// 对外暴露的文本容器
lv_obj_t *ui_TextContainer = NULL;

// 对外暴露的Menu1容器
lv_obj_t *ui_Menu1 = NULL;

// 对外暴露的指示线
lv_obj_t *ui_BrightnessLine = NULL;
lv_obj_t *ui_AiTalkLine = NULL;

// 对外暴露的录像机容器
lv_obj_t *ui_VideoContainer = NULL;

// 对外暴露的录像机文字标签
lv_obj_t *ui_CameraText = NULL;
lv_obj_t *ui_VideoText = NULL;
lv_obj_t *ui_RecordText = NULL;
lv_obj_t *ui_VideoRecordingContainer = NULL;  // 全局定义

// 对外暴露的Menu3文字标签
lv_obj_t *ui_MemoText = NULL;
lv_obj_t *ui_MoreText = NULL;

// 对外暴露的提词器相关控件
lv_obj_t *ui_TeleprompterRecorderRect = NULL;
lv_obj_t *ui_TeleprompterText = NULL;
lv_obj_t *ui_TeleprompterT = NULL;

// 对外暴露的提词器容器和文字控件
lv_obj_t *ui_TeleprompTerContainer = NULL;
lv_obj_t *ui_TeleprompTerTxT = NULL;

// 对外暴露的Menu3容器
lv_obj_t *ui_Menu3 = NULL;

// 对外暴露的subMenu容器
lv_obj_t *ui_subMenu = NULL;

// 对外暴露的subMenu文字标签
lv_obj_t *ui_SubMenu_Translate = NULL;
lv_obj_t *ui_SubMenu_Navigation = NULL;
lv_obj_t *ui_SubMenu_DisplayImage = NULL;
lv_obj_t *ui_SubMenu_ASR = NULL;
lv_obj_t *ui_SubMenu_Sleep = NULL;
lv_obj_t *ui_SubMenu_Personalize = NULL;
lv_obj_t *ui_SubMenu_Attitude = NULL;  // 姿态
lv_obj_t *ui_SubMenu_Exit = NULL;     // 退出
lv_obj_t *ui_SubMenu_Dial = NULL;     // 拨通
lv_obj_t *ui_SubMenu_Volume = NULL;   // 音量
// 对外暴露的subMenu矩形
lv_obj_t *ui_SubMenu_Rect = NULL;     // subMenu矩形指示器

// 对外暴露的选中框
lv_obj_t *ui_SelectionRect = NULL;    // 首页选中框


void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    
    // 设置屏幕背景为黑色
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    //yf
    lv_obj_set_width(ui_Screen1, 0);
        
    // [DELETED] TextContainer, Teleprompter, Menu1 creation logic

    
    // [DELETED] Menu1 border/shadow removal - Menu1 no longer exists

    // 创建录像机容器（270x480），居中显示，默认隐藏
    ui_VideoRecordingContainer = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_VideoRecordingContainer, 270, 480);
    lv_obj_center(ui_VideoRecordingContainer);
    lv_obj_set_style_bg_color(ui_VideoRecordingContainer, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VideoRecordingContainer, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VideoRecordingContainer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VideoRecordingContainer, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VideoRecordingContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_VideoRecordingContainer, LV_OBJ_FLAG_HIDDEN);

    // [DELETED] Menu1 children (SpeechBubble, Lines, Circle etc)


    // 创建录像机容器
    ui_VideoContainer = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_VideoContainer, 640, 480);  // 全屏大小
    lv_obj_set_pos(ui_VideoContainer, 0, 0);
    lv_obj_set_style_bg_color(ui_VideoContainer, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VideoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);  // 完全透明背景
    lv_obj_set_style_pad_all(ui_VideoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_VideoContainer, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_border_width(ui_VideoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_VideoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_VideoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_VideoContainer, LV_OBJ_FLAG_HIDDEN);  // 默认隐藏

    // 创建录像机图标
    // 右边的80×80圆角矩形，向右偏移21像素
    ui_VideoRecorderRect = lv_obj_create(ui_VideoContainer);
    lv_obj_set_width(ui_VideoRecorderRect, 80);
    lv_obj_set_height(ui_VideoRecorderRect, 80);
    lv_obj_set_x(ui_VideoRecorderRect, 13);  // 向右偏移13像素（21-8=13）
    lv_obj_set_y(ui_VideoRecorderRect, -80);  // 向上移动80像素
    lv_obj_set_align(ui_VideoRecorderRect, LV_ALIGN_CENTER);
    
    // 设置圆角矩形样式
    lv_obj_set_style_radius(ui_VideoRecorderRect, 12, LV_PART_MAIN | LV_STATE_DEFAULT);  // 增大圆角到12像素
    lv_obj_set_style_bg_color(ui_VideoRecorderRect, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 黑色背景（空心效果）
    lv_obj_set_style_bg_opa(ui_VideoRecorderRect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);  // 背景透明（空心效果）
    lv_obj_set_style_border_width(ui_VideoRecorderRect, 4, LV_PART_MAIN | LV_STATE_DEFAULT);  // 4像素边框
    lv_obj_set_style_border_color(ui_VideoRecorderRect, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 白色边框
    lv_obj_set_style_border_opa(ui_VideoRecorderRect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);  // 边框不透明
    
    // 移除默认的滚动标志
    lv_obj_clear_flag(ui_VideoRecorderRect, LV_OBJ_FLAG_SCROLLABLE);
    
    // 创建后立即隐藏录像机矩形
    // lv_obj_add_flag(ui_VideoRecorderRect, LV_OBJ_FLAG_HIDDEN);
    
    // 左边的三条线组成录像机图标
    // 第一条：竖线 267,137 到 267,183
    ui_VideoLine1 = lv_line_create(ui_VideoContainer);
    static lv_point_t video_line1_points[] = {{267, 137}, {267, 183}};
    lv_line_set_points(ui_VideoLine1, video_line1_points, 2);
    lv_obj_set_x(ui_VideoLine1, 0);
    lv_obj_set_y(ui_VideoLine1, 0);
    lv_obj_set_style_line_width(ui_VideoLine1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_VideoLine1, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_VideoLine1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏第一条线
    //lv_obj_add_flag(ui_VideoLine1, LV_OBJ_FLAG_HIDDEN);
    
    // 第二条：斜线 267,137 到 293,151
    ui_VideoLine2 = lv_line_create(ui_VideoContainer);
    static lv_point_t video_line2_points[] = {{267, 137}, {293, 151}};
    lv_line_set_points(ui_VideoLine2, video_line2_points, 2);
    lv_obj_set_x(ui_VideoLine2, 0);
    lv_obj_set_y(ui_VideoLine2, 0);
    lv_obj_set_style_line_width(ui_VideoLine2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_VideoLine2, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_VideoLine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏第二条线
    // lv_obj_add_flag(ui_VideoLine2, LV_OBJ_FLAG_HIDDEN);
    
    // 第三条：斜线 267,183 到 293,174
    ui_VideoLine3 = lv_line_create(ui_VideoContainer);
    static lv_point_t video_line3_points[] = {{267, 183}, {293, 174}};
    lv_line_set_points(ui_VideoLine3, video_line3_points, 2);
    lv_obj_set_x(ui_VideoLine3, 0);
    lv_obj_set_y(ui_VideoLine3, 0);
    lv_obj_set_style_line_width(ui_VideoLine3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_VideoLine3, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_VideoLine3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建后立即隐藏第三条线
    //lv_obj_add_flag(ui_VideoLine3, LV_OBJ_FLAG_HIDDEN);

    // [DELETED] Teleprompter extra items (T icon, Rect)


    // 创建新的录像机元件
    // 1. 圆形直径42，中央对齐位置在92，165
    lv_obj_t *ui_NewCircle1 = lv_obj_create(ui_VideoContainer);
    lv_obj_set_width(ui_NewCircle1, 42);
    lv_obj_set_height(ui_NewCircle1, 42);
    lv_obj_set_x(ui_NewCircle1, 92-21);
    lv_obj_set_y(ui_NewCircle1, 165-21);
    lv_obj_set_style_radius(ui_NewCircle1, 21, LV_PART_MAIN | LV_STATE_DEFAULT);  // 半径21像素，形成直径42像素的圆
    lv_obj_set_style_bg_color(ui_NewCircle1, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 黑色背景
    lv_obj_set_style_bg_opa(ui_NewCircle1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);  // 背景透明（空心效果）
    lv_obj_set_style_border_width(ui_NewCircle1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);  // 4像素边框
    lv_obj_set_style_border_color(ui_NewCircle1, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 白色边框
    lv_obj_set_style_border_opa(ui_NewCircle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_NewCircle1, LV_OBJ_FLAG_SCROLLABLE);
    // lv_obj_add_flag(ui_NewCircle1, LV_OBJ_FLAG_HIDDEN);  // 默认隐藏

    // 2. 圆角矩形长宽都是81，线宽4，中央对齐位置在92，165
    lv_obj_t *ui_NewRect1 = lv_obj_create(ui_VideoContainer);
    lv_obj_set_width(ui_NewRect1, 81);
    lv_obj_set_height(ui_NewRect1, 81);
    lv_obj_set_x(ui_NewRect1, 92-40);
    lv_obj_set_y(ui_NewRect1, 165-40);
    lv_obj_set_style_radius(ui_NewRect1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);  // 圆角半径
    lv_obj_set_style_bg_color(ui_NewRect1, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 黑色背景
    lv_obj_set_style_bg_opa(ui_NewRect1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);  // 背景透明（空心效果）
    lv_obj_set_style_border_width(ui_NewRect1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);  // 4像素边框
    lv_obj_set_style_border_color(ui_NewRect1, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 白色边框
    lv_obj_set_style_border_opa(ui_NewRect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_NewRect1, LV_OBJ_FLAG_SCROLLABLE);
    // lv_obj_add_flag(ui_NewRect1, LV_OBJ_FLAG_HIDDEN);  // 默认隐藏

    // 3. 圆形中央位置在121，138，圆形直径6像素实心
    lv_obj_t *ui_NewFillCircle = lv_obj_create(ui_VideoContainer);
    lv_obj_set_width(ui_NewFillCircle, 6);
    lv_obj_set_height(ui_NewFillCircle, 6);
    lv_obj_set_x(ui_NewFillCircle, 121);
    lv_obj_set_y(ui_NewFillCircle, 138);
    lv_obj_set_style_radius(ui_NewFillCircle, 3, LV_PART_MAIN | LV_STATE_DEFAULT);  // 半径3像素，形成直径6像素的圆
    lv_obj_set_style_bg_color(ui_NewFillCircle, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);  // 白色实心
    lv_obj_set_style_bg_opa(ui_NewFillCircle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);  // 完全不透明
    lv_obj_clear_flag(ui_NewFillCircle, LV_OBJ_FLAG_SCROLLABLE);
    // lv_obj_add_flag(ui_NewFillCircle, LV_OBJ_FLAG_HIDDEN);  // 默认隐藏

    // 创建拍照文字标签
    ui_CameraText = lv_label_create(ui_VideoContainer);
    lv_obj_set_width(ui_CameraText, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_CameraText, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_CameraText, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(ui_CameraText, 60-10, 239);  // 位置：50, 239
    lv_label_set_text(ui_CameraText, "拍照");
    lv_obj_set_style_text_font(ui_CameraText, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CameraText, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CameraText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_add_flag(ui_CameraText, LV_OBJ_FLAG_HIDDEN);  // 默认隐藏

    // 创建录像文字标签
    ui_VideoText = lv_label_create(ui_VideoContainer);
    lv_obj_set_width(ui_VideoText, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_VideoText, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_VideoText, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(ui_VideoText, 250+26, 239);  // 位置：250, 239
    lv_label_set_text(ui_VideoText, "录像");
    lv_obj_set_style_text_font(ui_VideoText, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_VideoText, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VideoText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_add_flag(ui_VideoText, LV_OBJ_FLAG_HIDDEN);  // 默认隐藏

    // [DELETED] Menu3 creation and old children (Recorder/Memo)


    // 在VideoContainer中创建一个竖直圆角矩形（居中对齐），参考录像机矩形样式
    lv_obj_t *ui_Menu3CenterRect = lv_obj_create(ui_VideoContainer); // Reparented to VideoContainer
    lv_obj_set_width(ui_Menu3CenterRect, 8);
    lv_obj_set_height(ui_Menu3CenterRect, 60);
    lv_obj_set_x(ui_Menu3CenterRect, 227); // 居中在 More 列 (选中框中心约547)
    lv_obj_set_y(ui_Menu3CenterRect, -80);
    lv_obj_set_align(ui_Menu3CenterRect, LV_ALIGN_CENTER);
    // 样式与录像机矩形一致：空心、白边、黑底透明
    lv_obj_set_style_radius(ui_Menu3CenterRect, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu3CenterRect, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu3CenterRect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Menu3CenterRect, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Menu3CenterRect, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Menu3CenterRect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_Menu3CenterRect, LV_OBJ_FLAG_SCROLLABLE);

    // 在VideoContainer中创建一个横向圆角矩形（与上面的竖直矩形组成十字）
    lv_obj_t *ui_Menu3CenterRectH = lv_obj_create(ui_VideoContainer); // Reparented to VideoContainer
    lv_obj_set_width(ui_Menu3CenterRectH, 60);
    lv_obj_set_height(ui_Menu3CenterRectH, 8);
    lv_obj_set_x(ui_Menu3CenterRectH, 227); // 居中在 More 列
    lv_obj_set_y(ui_Menu3CenterRectH, -80);
    lv_obj_set_align(ui_Menu3CenterRectH, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Menu3CenterRectH, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu3CenterRectH, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu3CenterRectH, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Menu3CenterRectH, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Menu3CenterRectH, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Menu3CenterRectH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_Menu3CenterRectH, LV_OBJ_FLAG_SCROLLABLE);

    // 在VideoContainer中创建"更多"文字标签（中列位置）
    ui_MoreText = lv_label_create(ui_VideoContainer); // Reparented to VideoContainer
    lv_obj_set_width(ui_MoreText, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_MoreText, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_MoreText, LV_ALIGN_TOP_LEFT);
    lv_obj_set_pos(ui_MoreText, 500, 239); // 居中在 More 列
    lv_label_set_text(ui_MoreText, "更多");
    lv_obj_set_style_text_font(ui_MoreText, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MoreText, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);

    // [DELETED] Rest of Menu1 children

    // [DELETED] Remainder of Menu1 debris (Aitalk config, Brightness, Lines, StatusLabel)

    // 创建选中框矩形 (用于高亮显示当前选中的菜单项)
    ui_SelectionRect = lv_obj_create(ui_VideoContainer);
    lv_obj_set_size(ui_SelectionRect, 173, 200);  // 宽度增加1/3 (130*1.33≈173)
    lv_obj_set_pos(ui_SelectionRect, 5, 110);     // 默认在Camera位置
    lv_obj_set_style_bg_opa(ui_SelectionRect, LV_OPA_TRANSP, 0);  // 背景透明
    lv_obj_set_style_border_width(ui_SelectionRect, 2, 0);        // 2像素边框
    lv_obj_set_style_border_color(ui_SelectionRect, lv_color_white(), 0);  // 白色边框
    lv_obj_set_style_border_opa(ui_SelectionRect, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(ui_SelectionRect, 12, 0);  // 圆角
    lv_obj_clear_flag(ui_SelectionRect, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_move_background(ui_SelectionRect);  // 移到最底层，不遮挡其他元素
    
    // 创建subMenu容器
    ui_subMenu = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_subMenu, 640, 450);  // 全屏大小
    lv_obj_set_pos(ui_subMenu, 0, 0);
    lv_obj_set_style_bg_color(ui_subMenu, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_subMenu, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_subMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_subMenu, LV_OBJ_FLAG_SCROLLABLE);
    
    // 移除边框
    lv_obj_set_style_border_width(ui_subMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_subMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_subMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 设置subMenu默认隐藏
    lv_obj_add_flag(ui_subMenu, LV_OBJ_FLAG_HIDDEN);
    
    // 第一行标签 (Y=239): 翻译、显示图
    // 翻译
    ui_SubMenu_Translate = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_Translate, 600);
    lv_obj_set_height(ui_SubMenu_Translate, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_Translate, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_Translate, "位置");
    lv_obj_set_pos(ui_SubMenu_Translate, 60-10, 239);
    lv_obj_set_style_text_font(ui_SubMenu_Translate, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_Translate, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_Translate, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_Translate, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 位置
    ui_SubMenu_Navigation = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_Navigation, 600);
    lv_obj_set_height(ui_SubMenu_Navigation, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_Navigation, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_Navigation, "电话");
    lv_obj_set_pos(ui_SubMenu_Navigation, 280-30-60, 239);
    lv_obj_set_style_text_font(ui_SubMenu_Navigation, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_Navigation, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_Navigation, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_Navigation, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 拨通
    ui_SubMenu_Dial = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_Dial, 600);
    lv_obj_set_height(ui_SubMenu_Dial, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_Dial, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_Dial, "/拨通");
    lv_obj_set_pos(ui_SubMenu_Dial, 280-30+40, 239);
    lv_obj_set_style_text_font(ui_SubMenu_Dial, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_Dial, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_Dial, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_Dial, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 显示图
    ui_SubMenu_DisplayImage = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_DisplayImage, 600);
    lv_obj_set_height(ui_SubMenu_DisplayImage, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_DisplayImage, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_DisplayImage, "显示图");
    lv_obj_set_pos(ui_SubMenu_DisplayImage, 508-80, 239);
    lv_obj_set_style_text_font(ui_SubMenu_DisplayImage, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_DisplayImage, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_DisplayImage, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_DisplayImage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 第二行标签 (Y=124): ASR、休眠、个性化
    // ASR
    ui_SubMenu_ASR = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_ASR, 600);
    lv_obj_set_height(ui_SubMenu_ASR, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_ASR, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_ASR, "接听");
    lv_obj_set_pos(ui_SubMenu_ASR, 60-10, 124);
    lv_obj_set_style_text_font(ui_SubMenu_ASR, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_ASR, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_ASR, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_ASR, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 休眠
    ui_SubMenu_Sleep = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_Sleep, 600);
    lv_obj_set_height(ui_SubMenu_Sleep, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_Sleep, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_Sleep, "休眠");
    lv_obj_set_pos(ui_SubMenu_Sleep, 280-30, 124);
    lv_obj_set_style_text_font(ui_SubMenu_Sleep, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_Sleep, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_Sleep, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_Sleep, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 个性化
    ui_SubMenu_Personalize = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_Personalize, 600);
    lv_obj_set_height(ui_SubMenu_Personalize, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_Personalize, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_Personalize, "个性化");
    lv_obj_set_pos(ui_SubMenu_Personalize, 428, 124);
    lv_obj_set_style_text_font(ui_SubMenu_Personalize, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_Personalize, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_Personalize, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_Personalize, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 第三行标签 (Y=310): 姿态、退出
    // 姿态
    ui_SubMenu_Attitude = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_Attitude, 600);
    lv_obj_set_height(ui_SubMenu_Attitude, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_Attitude, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_Attitude, "姿态");
    lv_obj_set_pos(ui_SubMenu_Attitude, 60-10, 310+50);
    lv_obj_set_style_text_font(ui_SubMenu_Attitude, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_Attitude, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_Attitude, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_Attitude, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 退出
    ui_SubMenu_Exit = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_Exit, 600);
    lv_obj_set_height(ui_SubMenu_Exit, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_Exit, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_Exit, "退出");
    lv_obj_set_pos(ui_SubMenu_Exit, 280-30, 310+50);
    lv_obj_set_style_text_font(ui_SubMenu_Exit, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_Exit, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_Exit, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_Exit, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 音量
    ui_SubMenu_Volume = lv_label_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_Volume, 600);
    lv_obj_set_height(ui_SubMenu_Volume, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_SubMenu_Volume, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_SubMenu_Volume, "音量");
    lv_obj_set_pos(ui_SubMenu_Volume, 428+12, 310+50);
    lv_obj_set_style_text_font(ui_SubMenu_Volume, &ui_font_alibaba_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SubMenu_Volume, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_long_mode(ui_SubMenu_Volume, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_line_space(ui_SubMenu_Volume, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 创建subMenu矩形指示器
    ui_SubMenu_Rect = lv_obj_create(ui_subMenu);
    lv_obj_set_width(ui_SubMenu_Rect, 58);
    lv_obj_set_height(ui_SubMenu_Rect, 2);
    lv_obj_set_pos(ui_SubMenu_Rect, 69, 174);
    lv_obj_set_style_radius(ui_SubMenu_Rect, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SubMenu_Rect, lv_color_white(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SubMenu_Rect, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SubMenu_Rect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(ui_SubMenu_Rect, LV_OBJ_FLAG_SCROLLABLE);
    //QuiT、IMUtest

    
}

