// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
extern lv_obj_t *ui_Label2;

lv_obj_t *ui_StatusLabel = NULL;
lv_obj_t *ui_TextContainer = NULL;
lv_obj_t *ui_Menu1 = NULL;
lv_obj_t *ui_BrightnessLine = NULL;
lv_obj_t *ui_AiTalkLine = NULL;
lv_obj_t *ui_VideoContainer = NULL;
lv_obj_t *ui_CameraText = NULL;
lv_obj_t *ui_VideoText = NULL;
lv_obj_t *ui_RecordText = NULL;
lv_obj_t *ui_VideoRecordingContainer = NULL;
lv_obj_t *ui_MemoText = NULL;
lv_obj_t *ui_MoreText = NULL;
lv_obj_t *ui_TeleprompterRecorderRect = NULL;
lv_obj_t *ui_TeleprompterText = NULL;
lv_obj_t *ui_TeleprompterT = NULL;
lv_obj_t *ui_TeleprompTerContainer = NULL;
lv_obj_t *ui_TeleprompTerTxT = NULL;
lv_obj_t *ui_Menu3 = NULL;
lv_obj_t *ui_subMenu = NULL;
lv_obj_t *ui_SubMenu_Translate = NULL;
lv_obj_t *ui_SubMenu_Navigation = NULL;
lv_obj_t *ui_SubMenu_DisplayImage = NULL;
lv_obj_t *ui_SubMenu_ASR = NULL;
lv_obj_t *ui_SubMenu_Sleep = NULL;
lv_obj_t *ui_SubMenu_Personalize = NULL;
lv_obj_t *ui_SubMenu_Attitude = NULL;
lv_obj_t *ui_SubMenu_Exit = NULL;
lv_obj_t *ui_SubMenu_Dial = NULL;
lv_obj_t *ui_SubMenu_Volume = NULL;
lv_obj_t *ui_SubMenu_Rect = NULL;
lv_obj_t *ui_SelectionRect = NULL;

// 蓝牙等待界面
lv_obj_t *ui_WaitBtContainer = NULL;
lv_obj_t *ui_WaitBtLabel = NULL;

// 场景单词文本显示界面
lv_obj_t *ui_SceneWordsContainer = NULL;
lv_obj_t *ui_SceneWordsTitle = NULL;
lv_obj_t *ui_SceneWordsText = NULL;
lv_obj_t *ui_SceneWordsHint = NULL;

// 拟境英语界面（原"英语对练"，复用 EnglishTalk* 符号名以兼容外部）
lv_obj_t *ui_EnglishTalkContainer = NULL;
lv_obj_t *ui_EnglishTalkTitle = NULL;
lv_obj_t *ui_EnglishTalkStatus = NULL;
lv_obj_t *ui_EnglishTalkTranscript = NULL;
lv_obj_t *ui_EnglishTalkHint = NULL;

// 拍照搜题界面
lv_obj_t *ui_PhotoSearchContainer = NULL;
lv_obj_t *ui_PhotoSearchTitle = NULL;
lv_obj_t *ui_PhotoSearchStatus = NULL;
lv_obj_t *ui_PhotoSearchCounter = NULL;
lv_obj_t *ui_PhotoSearchPath = NULL;
lv_obj_t *ui_PhotoSearchHint = NULL;

// 英语对练界面（第四张卡，新增）
lv_obj_t *ui_EnglishPracticeContainer = NULL;
lv_obj_t *ui_EnglishPracticeTitle = NULL;
lv_obj_t *ui_EnglishPracticeHint = NULL;

/* ---- 功能页通用样式参数（灰阶，适配光波导 4bpp） ---- */
#define PAGE_W              640
#define PAGE_H              480
#define PAGE_TITLE_Y        16
#define PAGE_DIVIDER_Y      60
#define PAGE_FOOTER_Y       (PAGE_H - 36)
#define PAGE_BG             lv_color_black()
#define PAGE_TITLE_GRAY     lv_color_make(200, 200, 200)
#define PAGE_DIVIDER_GRAY   lv_color_make(90, 90, 90)
#define PAGE_STATUS_GRAY    lv_color_make(150, 150, 150)
#define PAGE_MUTED_GRAY     lv_color_make(110, 110, 110)
#define PAGE_HINT_GRAY      lv_color_make(80, 80, 80)

/* 公共：新建一个全屏功能页容器（无边框，黑背景，默认隐藏） */
static lv_obj_t *new_function_page(lv_obj_t *parent) {
    lv_obj_t *c = lv_obj_create(parent);
    lv_obj_set_size(c, PAGE_W, PAGE_H);
    lv_obj_set_pos(c, 0, 0);
    lv_obj_set_style_bg_color(c, PAGE_BG, 0);
    lv_obj_set_style_bg_opa(c, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(c, 0, 0);
    lv_obj_set_style_pad_all(c, 0, 0);
    lv_obj_clear_flag(c, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(c, LV_OBJ_FLAG_HIDDEN);
    return c;
}

/* 公共：底部"双击返回主页"提示 */
static lv_obj_t *build_page_footer(lv_obj_t *parent, const char *text) {
    lv_obj_t *hint = lv_label_create(parent);
    lv_label_set_text(hint, text);
    lv_obj_set_style_text_font(hint, &ui_font_alibaba_30, 0);
    lv_obj_set_style_text_color(hint, PAGE_HINT_GRAY, 0);
    lv_obj_align(hint, LV_ALIGN_BOTTOM_MID, 0, -18);
    return hint;
}


void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(ui_Screen1, LV_OPA_COVER, 0);
    /* 去掉默认主题可能加在屏幕上的边框和 padding，避免首页出现上下框线 */
    lv_obj_set_style_border_width(ui_Screen1, 0, 0);
    lv_obj_set_style_pad_all(ui_Screen1, 0, 0);
    lv_obj_set_style_outline_width(ui_Screen1, 0, 0);

    // ==================== 蓝牙等待界面 ====================
    ui_WaitBtContainer = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_WaitBtContainer, 640, 480);
    lv_obj_set_pos(ui_WaitBtContainer, 0, 0);
    lv_obj_set_style_bg_color(ui_WaitBtContainer, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(ui_WaitBtContainer, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(ui_WaitBtContainer, 0, 0);
    lv_obj_clear_flag(ui_WaitBtContainer, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_WaitBtContainer, LV_OBJ_FLAG_HIDDEN);

    // 蓝牙图标（使用文字模拟）
    lv_obj_t *bt_icon = lv_label_create(ui_WaitBtContainer);
    lv_label_set_text(bt_icon, LV_SYMBOL_BLUETOOTH);
    lv_obj_set_style_text_font(bt_icon, &lv_font_montserrat_48, 0);
    lv_obj_set_style_text_color(bt_icon, lv_color_make(80, 140, 255), 0);
    lv_obj_align(bt_icon, LV_ALIGN_CENTER, 0, -80);

    ui_WaitBtLabel = lv_label_create(ui_WaitBtContainer);
    lv_label_set_text(ui_WaitBtLabel, "请连接手机蓝牙...");
    lv_obj_set_style_text_font(ui_WaitBtLabel, &ui_font_alibaba_48, 0);
    lv_obj_set_style_text_color(ui_WaitBtLabel, lv_color_white(), 0);
    lv_obj_set_style_text_align(ui_WaitBtLabel, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_align(ui_WaitBtLabel, LV_ALIGN_CENTER, 0, 20);

    lv_obj_t *bt_hint = lv_label_create(ui_WaitBtContainer);
    lv_label_set_text(bt_hint, "请在手机APP中搜索并连接 OSAIG");
    lv_obj_set_style_text_font(bt_hint, &ui_font_alibaba_30, 0);
    lv_obj_set_style_text_color(bt_hint, lv_color_make(100, 100, 100), 0);
    lv_obj_set_style_text_align(bt_hint, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_align(bt_hint, LV_ALIGN_CENTER, 0, 100);

    // ==================== 首页容器 ====================
    ui_VideoContainer = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_VideoContainer, 640, 480);
    lv_obj_set_pos(ui_VideoContainer, 0, 0);
    lv_obj_set_style_bg_opa(ui_VideoContainer, 0, 0);
    lv_obj_set_style_pad_all(ui_VideoContainer, 0, 0);
    lv_obj_set_style_border_width(ui_VideoContainer, 0, 0);
    lv_obj_clear_flag(ui_VideoContainer, LV_OBJ_FLAG_SCROLLABLE);

    /* 首页四项布局：
     *   - 屏幕宽 640，外边距 16，卡片宽 140，间距 16
     *   - 位置 x：16, 172, 328, 484 （末端 484+140=624，右边距 16）*/
    #define BOX_W 140
    #define BOX_H 190
    #define BOX_Y 120
    #define BOX_X0 16
    #define BOX_DX 156      /* BOX_W + 间距 = 140 + 16 */
    #define BOX_RADIUS 16
    #define BOX_BORDER 3

    // --- 框1: 场景单词 ---
    lv_obj_t *box1 = lv_obj_create(ui_VideoContainer);
    lv_obj_set_size(box1, BOX_W, BOX_H);
    lv_obj_set_pos(box1, BOX_X0 + 0 * BOX_DX, BOX_Y);
    lv_obj_set_style_bg_opa(box1, 0, 0);
    lv_obj_set_style_border_width(box1, BOX_BORDER, 0);
    lv_obj_set_style_border_color(box1, lv_color_white(), 0);
    lv_obj_set_style_radius(box1, BOX_RADIUS, 0);
    lv_obj_clear_flag(box1, LV_OBJ_FLAG_SCROLLABLE);

    ui_CameraText = lv_label_create(box1);
    lv_label_set_text(ui_CameraText, "场景\n单词");
    lv_obj_set_style_text_font(ui_CameraText, &ui_font_alibaba_48, 0);
    lv_obj_set_style_text_color(ui_CameraText, lv_color_white(), 0);
    lv_obj_set_style_text_align(ui_CameraText, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_line_space(ui_CameraText, 8, 0);
    lv_obj_center(ui_CameraText);

    // --- 框2: 拟境英语 ---
    lv_obj_t *box2 = lv_obj_create(ui_VideoContainer);
    lv_obj_set_size(box2, BOX_W, BOX_H);
    lv_obj_set_pos(box2, BOX_X0 + 1 * BOX_DX, BOX_Y);
    lv_obj_set_style_bg_opa(box2, 0, 0);
    lv_obj_set_style_border_width(box2, BOX_BORDER, 0);
    lv_obj_set_style_border_color(box2, lv_color_white(), 0);
    lv_obj_set_style_radius(box2, BOX_RADIUS, 0);
    lv_obj_clear_flag(box2, LV_OBJ_FLAG_SCROLLABLE);

    ui_VideoText = lv_label_create(box2);
    lv_label_set_text(ui_VideoText, "拟境\n英语");
    lv_obj_set_style_text_font(ui_VideoText, &ui_font_alibaba_48, 0);
    lv_obj_set_style_text_color(ui_VideoText, lv_color_white(), 0);
    lv_obj_set_style_text_align(ui_VideoText, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_line_space(ui_VideoText, 8, 0);
    lv_obj_center(ui_VideoText);

    // --- 框3: 拍照搜题 ---
    lv_obj_t *box3 = lv_obj_create(ui_VideoContainer);
    lv_obj_set_size(box3, BOX_W, BOX_H);
    lv_obj_set_pos(box3, BOX_X0 + 2 * BOX_DX, BOX_Y);
    lv_obj_set_style_bg_opa(box3, 0, 0);
    lv_obj_set_style_border_width(box3, BOX_BORDER, 0);
    lv_obj_set_style_border_color(box3, lv_color_white(), 0);
    lv_obj_set_style_radius(box3, BOX_RADIUS, 0);
    lv_obj_clear_flag(box3, LV_OBJ_FLAG_SCROLLABLE);

    ui_MoreText = lv_label_create(box3);
    lv_label_set_text(ui_MoreText, "拍照\n搜题");
    lv_obj_set_style_text_font(ui_MoreText, &ui_font_alibaba_48, 0);
    lv_obj_set_style_text_color(ui_MoreText, lv_color_white(), 0);
    lv_obj_set_style_text_align(ui_MoreText, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_line_space(ui_MoreText, 8, 0);
    lv_obj_center(ui_MoreText);

    // --- 框4: 英语对练（新增）---
    lv_obj_t *box4 = lv_obj_create(ui_VideoContainer);
    lv_obj_set_size(box4, BOX_W, BOX_H);
    lv_obj_set_pos(box4, BOX_X0 + 3 * BOX_DX, BOX_Y);
    lv_obj_set_style_bg_opa(box4, 0, 0);
    lv_obj_set_style_border_width(box4, BOX_BORDER, 0);
    lv_obj_set_style_border_color(box4, lv_color_white(), 0);
    lv_obj_set_style_radius(box4, BOX_RADIUS, 0);
    lv_obj_clear_flag(box4, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *box4_text = lv_label_create(box4);
    lv_label_set_text(box4_text, "英语\n对练");
    lv_obj_set_style_text_font(box4_text, &ui_font_alibaba_48, 0);
    lv_obj_set_style_text_color(box4_text, lv_color_white(), 0);
    lv_obj_set_style_text_align(box4_text, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_line_space(box4_text, 8, 0);
    lv_obj_center(box4_text);

    // --- 首页底部操作说明 ---
    lv_obj_t *home_hint = lv_label_create(ui_VideoContainer);
    lv_label_set_text(home_hint,
                      "单击触摸板1 翻页   ·   长按触摸板1 进入功能");
    lv_obj_set_style_text_font(home_hint, &ui_font_alibaba_30, 0);
    lv_obj_set_style_text_color(home_hint, lv_color_make(150, 150, 150), 0);
    lv_obj_set_style_text_align(home_hint, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_align(home_hint, LV_ALIGN_BOTTOM_MID, 0, -30);

    // --- 选中框（首页唯一的圆角框，做当前选中高亮） ---
    ui_SelectionRect = lv_obj_create(ui_VideoContainer);
    lv_obj_set_size(ui_SelectionRect, BOX_W + 8, BOX_H + 8);
    lv_obj_set_pos(ui_SelectionRect, BOX_X0 - 4, BOX_Y - 4);
    lv_obj_set_style_bg_opa(ui_SelectionRect, 30, 0);
    lv_obj_set_style_bg_color(ui_SelectionRect, lv_color_white(), 0);
    lv_obj_set_style_border_width(ui_SelectionRect, 3, 0);
    lv_obj_set_style_border_color(ui_SelectionRect, lv_color_white(), 0);
    lv_obj_set_style_border_opa(ui_SelectionRect, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(ui_SelectionRect, BOX_RADIUS + 4, 0);
    lv_obj_clear_flag(ui_SelectionRect, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_move_background(ui_SelectionRect);

    /* 旧的 ui_subMenu 占位保留但不使用（主程序不再切到它），
     * 避免外部仍有 ui_subMenu 的引用破坏链接。*/
    ui_subMenu = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_subMenu, 1, 1);
    lv_obj_set_pos(ui_subMenu, 0, 0);
    lv_obj_set_style_border_width(ui_subMenu, 0, 0);
    lv_obj_set_style_bg_opa(ui_subMenu, 0, 0);
    lv_obj_clear_flag(ui_subMenu, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(ui_subMenu, LV_OBJ_FLAG_HIDDEN);

    /* 三个功能页面：按用户要求，只保留
     *   - 最上面一行：功能名
     *   - 最下面一行：单击触摸板2退出功能
     * 中间不额外装饰，保持极简。*/
    const char *kExitHint = "单击触摸板2 退出功能";

    // ==================== 场景单词页面 ====================
    ui_SceneWordsContainer = new_function_page(ui_Screen1);
    ui_SceneWordsTitle = lv_label_create(ui_SceneWordsContainer);
    lv_label_set_text(ui_SceneWordsTitle, "场景单词");
    lv_obj_set_style_text_font(ui_SceneWordsTitle, &ui_font_alibaba_48, 0);
    lv_obj_set_style_text_color(ui_SceneWordsTitle, lv_color_white(), 0);
    lv_obj_align(ui_SceneWordsTitle, LV_ALIGN_TOP_MID, 0, 20);
    ui_SceneWordsText = NULL;  /* 暂不使用，保留符号供外部兼容 */
    ui_SceneWordsHint = build_page_footer(ui_SceneWordsContainer, kExitHint);

    // ==================== 拟境英语页面 ====================
    ui_EnglishTalkContainer = new_function_page(ui_Screen1);
    ui_EnglishTalkTitle = lv_label_create(ui_EnglishTalkContainer);
    lv_label_set_text(ui_EnglishTalkTitle, "拟境英语");
    lv_obj_set_style_text_font(ui_EnglishTalkTitle, &ui_font_alibaba_48, 0);
    lv_obj_set_style_text_color(ui_EnglishTalkTitle, lv_color_white(), 0);
    lv_obj_align(ui_EnglishTalkTitle, LV_ALIGN_TOP_MID, 0, 20);
    ui_EnglishTalkStatus     = NULL;
    ui_EnglishTalkTranscript = NULL;
    ui_EnglishTalkHint = build_page_footer(ui_EnglishTalkContainer, kExitHint);

    // ==================== 拍照搜题页面 ====================
    ui_PhotoSearchContainer = new_function_page(ui_Screen1);
    ui_PhotoSearchTitle = lv_label_create(ui_PhotoSearchContainer);
    lv_label_set_text(ui_PhotoSearchTitle, "拍照搜题");
    lv_obj_set_style_text_font(ui_PhotoSearchTitle, &ui_font_alibaba_48, 0);
    lv_obj_set_style_text_color(ui_PhotoSearchTitle, lv_color_white(), 0);
    lv_obj_align(ui_PhotoSearchTitle, LV_ALIGN_TOP_MID, 0, 20);
    ui_PhotoSearchStatus  = NULL;
    ui_PhotoSearchCounter = NULL;
    ui_PhotoSearchPath    = NULL;
    ui_PhotoSearchHint = build_page_footer(ui_PhotoSearchContainer, kExitHint);

    // ==================== 英语对练页面（第四张卡）====================
    ui_EnglishPracticeContainer = new_function_page(ui_Screen1);
    ui_EnglishPracticeTitle = lv_label_create(ui_EnglishPracticeContainer);
    lv_label_set_text(ui_EnglishPracticeTitle, "英语对练");
    lv_obj_set_style_text_font(ui_EnglishPracticeTitle, &ui_font_alibaba_48, 0);
    lv_obj_set_style_text_color(ui_EnglishPracticeTitle, lv_color_white(), 0);
    lv_obj_align(ui_EnglishPracticeTitle, LV_ALIGN_TOP_MID, 0, 20);
    ui_EnglishPracticeHint = build_page_footer(ui_EnglishPracticeContainer, kExitHint);
}

